################ English language ##################
[it]
languageName = "It"
languageCode = "it-it"
contentDir = "content/italian"
weight = 1

[en]
  languageName = "En"
  languageCode = "en-en"
  contentDir = "content/english"
  weight = 2
