################ English language ##################
[it]
languageName = "It"
languageCode = "it-it"
contentDir = "content/italian"
weight = 10

[en]
  languageName = "En"
  languageCode = "en-GB"
  contentDir = "content/english"
  weight = 20
