############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1
title = "Outdoor, turism and camping map building"

[[main]]
name = "Sample"
url = "/examples-of-3d-outdoor-and-territory-maps/"
weight = 2
title = "Examples of camping, village, outdoor and territory maps"

[[main]]
name = "Maps types"
weight = 3

[[main]]
name = "Camping and village Maps"
parent = "Maps types"
url = "/making-maps-for-campsite-turist-villages/"
weight = 1
title = "Camping, campsite and village Maps creator"

[[main]]
name = "Trekking and MTB Maps"
url = "/creation-of-trekking-and-mtb-trail-maps/"
weight = 2
title = "Trekking and MTB Maps creator"
parent = "Maps types"



[[main]]
name = "About"
url = "/about"
weight = 4
title = "About Outdoor 3D Map"



[[main]]
name = "Contacts"
url = "/contacts"
weight = 5
title = "Contacts Outdoor 3D Map"

# [[main]]
# name = "Blog"
# url = "/blog"
# weight = 6
# title = "Blog Outdoor 3D Map"






# footer menu


# [[footer]]
# name = "Home"
# url = "/"
# weight = 1
